Repository idom-team/django-idom, pull requests merged in 2022-09, with the labels that each got.

#86 use_query and use_mutation
  .github/workflows/publish-docs.yml
  .github/workflows/publish-py.yml
  .github/workflows/test-docs.yml
  .github/workflows/test-src.yml
  CHANGELOG.md
  docs/features/decorators.md
  docs/features/hooks.md
  docs/features/orm.md
  mkdocs.yml
  noxfile.py
  pyproject.toml
  requirements/build-docs.txt
  requirements/pkg-deps.txt
  requirements/test-env.txt
  setup.py
  src/django_idom/hooks.py
  src/django_idom/types.py
  src/js/package-lock.json
  src/js/package.json
  tests/test_app/admin.py
  tests/test_app/components.py
  tests/test_app/migrations/0001_initial.py
  tests/test_app/models.py
  tests/test_app/settings.py
  tests/test_app/static/django-css-test.css
  tests/test_app/templates/base.html
  tests/test_app/tests/test_components.py
  tests/test_app/urls.py
Labels: type: feature, type: investigation

#96 Allow whitespace characters within component regex
  CHANGELOG.md
  src/django_idom/utils.py
  tests/test_app/tests/test_regex.py
Labels: type: revision

#81 View to Component
  CHANGELOG.md
  docs/changelog/index.md
  docs/contribute/running-tests.md
  docs/features/components.md
  docs/getting-started/learn-more.md
  docs/includes/examples.md
  docs/index.md
  docs/src/changelog/index.md
  docs/src/contribute/django-idom.md
  docs/src/contribute/docs.md
  docs/src/contribute/running-tests.md
  docs/src/features/components.md
  docs/src/features/decorators.md
  docs/src/features/hooks.md
  docs/src/features/settings.md
  docs/src/features/templatetag.md
  docs/src/getting-started/create-component.md
  docs/src/getting-started/initial-steps.md
  docs/src/getting-started/learn-more.md
  docs/src/getting-started/reference-component.md
  docs/src/getting-started/render-view.md
  docs/src/index.md
  docs/src/installation/index.md
  docs/src/stylesheets/extra.css
  mkdocs.yml
  noxfile.py
  src/django_idom/__init__.py
  src/django_idom/components.py
  src/django_idom/config.py
  src/django_idom/decorators.py
  src/django_idom/http/urls.py
  src/django_idom/http/views.py
  src/django_idom/types.py
  src/django_idom/utils.py
  tests/test_app/components.py
  tests/test_app/static/django-css-test.css
  tests/test_app/templates/base.html
  tests/test_app/templates/view_to_component.html
  tests/test_app/templates/view_to_component_script.html
  tests/test_app/tests/test_components.py
  tests/test_app/views.py
Labels: type: feature
